# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lego Sailor
email: masterbuilder271+sailor@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Josh. I sail and I build Lego. Sometimes I combine the two.
#twitter_username: username
#github_username: username
#minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  #- jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name   : "Joshua"
  avatar : "/assets/images/bio-photo.png"
  bio    : "Hi, I'm Josh. I'm 13 and sail an Optimist out of Connells Point Sailing Club, Sydney. I have been building Lego since forever. Recently I have combined the two!"
  links:

    #- label: "Email"
    #  icon: "fab fa-fw fa-envelope"
    #  url: "mailto:masterbuilder271+sailor@gmail.com"s

footer:
  links:
    - label: "LegoSailor"
      icon: "fab fa-fw fa-github"
      url: "https://legosailor.github.io/"
#
    #- label: "Email"
    #  icon: "fab fa-fw fa-envelope"
    #  url: "mailto:masterbuilder271+sailor@gmail.com"
    
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
